
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnycbggaddexobvziuco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhueWNiZ2dhZGRleG9idnppdWNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MTU0ODMsImV4cCI6MjA1ODA5MTQ4M30.pdXfpFQjxszTNrN2VIWYT7FNtRFAOnEkWhvK1XVapQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage,
  },
});
